set pnep url to be blank when no forecast is available
iridl/x24-vector pull request #43
Opened 2022-02-03 18:21 UTC by kgraaf

This solves the issue of erroneous forecast raster data being "left behind" when updated to a month for which there is no forecast

2022-02-03 19:25 UTC, aaron-kaplan requested changes
If possible, it would be nice to display a message over the map saying something like "no forecast available for issue month {date}."

Also a minor stylistic comment below.

2022-02-03 19:26 UTC, aaron-kaplan commented
If possible, it would be nice to display a message over the map saying something like "no forecast available for issue month {date}."

2022-02-03 19:34 UTC, kgraaf commented on fbfmaproom/fbfmaproom.py
> +    except:
Oh, that's a good point

2022-02-03 20:12 UTC, aaron-kaplan commented
I don't love having the message in the control bar. It's hard to notice. Would it be hard to overlay it on the map? That's where I'm looking when I'm looking for the missing forecast.

2022-02-03 20:19 UTC, aaron-kaplan commented
If you do manage to overlay the message on the map, try to configure it so that it only appears if the forecast layer is toggled on (visible).

2022-02-03 20:23 UTC, kgraaf commented
> I don't love having the message in the control bar. It's hard to notice. Would it be hard to overlay it on the map? That's where I'm looking when I'm looking for the missing forecast.

I can try and see

2022-02-03 20:36 UTC, kgraaf commented
Should the error message be placed in a tooltip like the "No Data" message?

2022-02-03 20:39 UTC, aaron-kaplan commented
The tooltip isn't visible on initial page load. If you want to make it appear immediately if there's no forecast available, that seems ok.

2022-02-04 18:07 UTC, aaron-kaplan commented on fbfmaproom/fbflayout.py
> +            ),
Does this block interaction until you dismiss it? If so, that seems too heavyweight. Can't we add a label in the center of the map? Maybe you could use a [tooltip](https://leafletjs.com/reference.html#tooltip) with `permanent=true`?

2022-02-04 21:10 UTC, aaron-kaplan commented on fbfmaproom/fbflayout.py
> +            ),
It doesn't block interaction.

2022-02-04 21:10 UTC, aaron-kaplan approved these changes

2022-02-04 21:12 UTC, merged